<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng Nhp_termsCheck</name>
   <tag></tag>
   <elementGuidId>a15f7548-0a68-466e-8b47-ddb76e5a164e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termsCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsCheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tôi đã đọc và chấp nhận điều khoản, chính sách&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5fd09fab-e10b-45b5-9944-90b928ebb6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>68f5cad6-b55d-465b-811d-4bcaa13d62a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f57a29f6-1ea8-426f-89d2-a023bf3ee921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsCheck</value>
      <webElementGuid>6cbca926-bed4-477b-99f4-4c38548839f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsCheck&quot;)</value>
      <webElementGuid>89f013f3-9dc3-4387-a4ab-6da430a1b77f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsCheck']</value>
      <webElementGuid>513e6ef6-1149-4128-965e-dd49a9f13246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contactform2']/div[4]/input</value>
      <webElementGuid>6b9240f4-9323-4404-9e50-d54961d52276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5f50273a-2f15-4ba9-8d07-408ddcd74c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'termsCheck']</value>
      <webElementGuid>29275db1-d5d5-43ab-9137-554b485fc59f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
