<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Register_exampleCheck</name>
   <tag></tag>
   <elementGuidId>f22c838e-dece-4590-ab68-6c77cffd2b36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleCheck</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleCheck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;I have read and accept the Terms and Privacy Policy&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cdcf766-6ec7-4f90-bbf2-f506eacc0fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e95122c7-1e2f-4704-bcad-d35b0e350679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-input</value>
      <webElementGuid>072bbb07-8c1c-4eaa-8d8c-af8951fbd48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleCheck</value>
      <webElementGuid>8a269fd0-a101-4ae0-a33f-7870e17d4457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactform2&quot;)/div[@class=&quot;form-group mb-2 d-flex&quot;]/input[@id=&quot;exampleCheck&quot;]</value>
      <webElementGuid>773efdfe-7f3e-449e-9af6-8ceac488a245</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleCheck']</value>
      <webElementGuid>6b26b40c-7c67-4e70-a110-35386a98ffdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='contactform2']/div[5]/input</value>
      <webElementGuid>c0933498-fb5d-44e9-843d-e82435d4e848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>c21d5b99-e69c-4cab-8ac1-c4afbbaaa5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exampleCheck']</value>
      <webElementGuid>2d499cb0-c7ce-472e-9162-b4a975d3ab54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
